name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode SSH key into file
        run: |
          echo "${{ secrets.VPS_SSH_KEY_B64 }}" | base64 -d > key.pem
          chmod 600 key.pem

      - name: Connect to VPS and restart app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key_path: key.pem
          script: |
            cd /root/nola_sdk_public
            git pull
            source venv/bin/activate
            pkill -f main_nola.py || true
            nohup python3 main_nola.py > log.txt 2>&1 &